### ISSUE TITLE
Notice Note template tag not rendering / showing raw

### ISSUE THREAD

**Issue by jeremytanner** [tinkerbell/tinkerbell-docs#110]
Notice template tags are not properly rendering their content

[Equinix Metal Setup with Terraform](https://docs.tinkerbell.org/setup/equinix-metal-terraform/)
[In repo ](https://github.com/tinkerbell/tinkerbell-docs/blob/master/docs/setup/equinix-metal-terraform.md)

## Expected Behaviour

Template tags should render out, styling the content they wrap

## Current Behaviour

`{{% notice note %}}` tags are not being rendered out

## Steps to Reproduce (for bugs)
1. Load [Equinix Metal Setup with Terraform](https://docs.tinkerbell.org/setup/equinix-metal-terraform/)
2. View the "Registering the Worker" section

## Your Environment
macOS 11.4 / Safari 14.1.1

**Comment by DailyAlice** [comment]
Looked into the formatting on this, and so far I have a branch/PR with basic mkdocs formatting. (https://github.com/tinkerbell/tinkerbell-docs/pull/113)

There is an option to extend our notice blocks function/design in mkdocs material, but my instinct is to go with the simple version for now. [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/).
