### ISSUE TITLE
Side navigation links can't be scrolled through once expanded past page length

### ISSUE THREAD

**Issue by gauravgahlot** [tinkerbell/tinkerbell-docs#117]
When all the navigation links are expanded, one is unable to scroll through the navigation. Even you hover over the sidebar, only the main is scrolled and you can never reach the end of the sidebar.

Please see the attached video for clarity.

https://user-images.githubusercontent.com/28539256/126098204-bd0c1e39-5448-46ff-9cef-eda5ee9fd9a1.mp4

**Comment by DailyAlice** [comment]
If it helps, I took a look at this locally, and stock mkdocs-material does not have this bug. If you remove the [theme overrides](https://github.com/tinkerbell/tinkerbell-docs/blob/e3e8f1f7ec26664082066c9878f86a5fca343624/mkdocs.yml#L60) from mkdocs.yml and load the site without them, a scroll bar will appear in the site navigation panel if it is extended below the bottom of the contents of the page.
