### ISSUE TITLE
example templates: describe why the volume mounts (/dev, /lib/firmware) are required

### ISSUE THREAD

**Issue by rgl** [tinkerbell/tinkerbell-docs#125]
The examples (e.g. [ubuntu](https://docs.tinkerbell.org/deploying-operating-systems/examples-ubuntu/) or [windows](https://docs.tinkerbell.org/deploying-operating-systems/examples-win/)) should describe why they use the following volume mounts:

```
    volumes:
      - /dev:/dev
      - /dev/console:/dev/console
      - /lib/firmware:/lib/firmware:ro
```

Maybe at https://docs.tinkerbell.org/deploying-operating-systems/the-deployment/

**Comment by tstromberg** [comment]
Thanks for the feedback @rgl - if you are up for attempting to document this, please let me know. I'd be happy to review a PR that does this.

@thebsdbox - do you have any insight into who/what uses these volume mounts?

**Comment by rgl** [comment]
@tstromberg, I'm only sure about `/dev`, which is needed when the action needs to write to a physical device like a disk.
