### ISSUE TITLE
Header and footer

### ISSUE THREAD

**Issue by ronggur** [tinkerbell/tinkerbell-docs#2]
sync header and footer to match https://tinkerbell.org/docs/

**Comment by felixwidjaja** [comment]
hi @geriadam Can you match the logo size & font sizes too? Thank you.

Change this:
<img width="1360" alt="Screen Shot 2020-09-21 at 10 10 24 PM" src="https://user-images.githubusercontent.com/4198376/93784500-4ba9e080-fc57-11ea-84b2-6753a797f2ea.png">

To this:
<img width="1244" alt="Screen Shot 2020-09-21 at 10 09 31 PM" src="https://user-images.githubusercontent.com/4198376/93784490-48aef000-fc57-11ea-93bb-d16c225cbef4.png">

**Comment by geriadam** [comment]
![image](https://user-images.githubusercontent.com/29569530/93791661-b579b880-fc5e-11ea-8505-7006697da186.png)

**Comment by felixwidjaja** [comment]
@geriadam Thanks looks better. One more thing: maybe a little bigger logo?

**Comment by geriadam** [comment]
> @geriadam Thanks looks better. One more thing: maybe a little bigger logo?

@felixwidjaja okey, i will try

**Comment by felixwidjaja** [comment]
@geriadam can you take a look again about the nav in header & active state?
In https://docs.tinkerbell.org/ you have: 

- Home
- FAQs
- Examples
- Community

It should be as my sshot above.

- FAQ's
- Docs [SHOULD BE ACTIVE]
- Examples
- Community

Thank you.

![image](https://user-images.githubusercontent.com/4198376/93967561-9def1c80-fd91-11ea-850b-c08fe5853f41.png)

**Comment by felixwidjaja** [comment]
@thomcrowe wish to have Youtube in the header.
@geriadam when you have time, please add.
![image](https://user-images.githubusercontent.com/4198376/94119663-6b205380-fe79-11ea-94c4-ed1ca18d7a82.png)
