### ISSUE TITLE
Document that workflows are rendered from templates and are immutable

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tinkerbell-docs#21]
@detiber expected a template update to trickle down to a workflow based on it and opened https://github.com/tinkerbell/tink/issues/292 when that did not happen. This is not-a-bug, but not explicitly described in the docs. We should make sure to document this.

**Comment by DailyAlice** [comment]
Do you think just a line about immutability in the first paragraph of the [workflow doc](https://docs.tinkerbell.org/about/workflows/) is sufficient?

I was just thinking something like, "Workflows are immutable. Updating a template or hardware data does not update existing workflows."

I'm on the fence whether more words are needed.

**Comment by detiber** [comment]
@DailyAlice I think that should be sufficient. I think it would have clarified my initial understanding at least.

**Comment by DailyAlice** [comment]
Out in production. Closing! 🎉
