### ISSUE TITLE
about/hardware-data.md shouldn't doc metadata

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tinkerbell-docs#23]
The hardware.metadata values are meant to be opaque to tinkerbell services and only really meant for use by workflows. The current examples is just what Equinix Metal happens to stuff into it, but not really relevant for any other operator. We should remove the example.

**Comment by DailyAlice** [comment]
hmmm, yeah it looks a bit heavy. 

Are there any required fields in hardware.metadata? Or anything that we might want to call out as specifically useful? Fields that people sort of use and might show up in the examples fairly often?

**Comment by DailyAlice** [comment]
I have a draft that I started back in July that I threw into a branch - https://github.com/DailyAlice/tinkerbell-docs/blob/hardware-data-example/docs/about/hardware-data.md.

I could remove the "Robust" example. Or both examples, but fill in some information about useful fields.

**Comment by DailyAlice** [comment]
Related, older issue from tinkerbell.org repo - https://github.com/tinkerbell/tinkerbell.org/issues/111
