### ISSUE TITLE
Packet to Equinix Metal re-brand

### ISSUE THREAD

**Issue by DailyAlice** [tinkerbell/tinkerbell-docs#26]
Need to audit and change instances of Packet to Equinix Metal in the docs.

**Comment by DailyAlice** [comment]
first-pass on branch: https://github.com/DailyAlice/tinkerbell-docs/tree/rebrand

**Comment by DailyAlice** [comment]
honestly, the first pass was pretty good, PR is open.

**Comment by felixwidjaja** [comment]
Looks good. Just merged it @DailyAlice

**Comment by DailyAlice** [comment]
Yay! thanks @felixwidjaja. Closing! 🎉
