### ISSUE TITLE
Copying code snippets through the copy button should only copy the command, not the output

### ISSUE THREAD

**Issue by mrmrcoleman** [tinkerbell/tinkerbell-docs#29]
Using the copy hoverover item on the docs copies the command _and the output_ when it should just copy the command.

## Expected Behaviour
<img width="846" alt="Screenshot 2020-11-26 at 17 30 51" src="https://user-images.githubusercontent.com/2339682/100379662-23e74800-300d-11eb-84d3-7eeefd539fff.png">

Only `docker exec -i deploy_tink-cli_1 tink hardware push < ./hardware-data.json` should be copied to the clipboard.

## Current Behaviour

All this is copied to the clipboard.

```
docker exec -i deploy_tink-cli_1 tink hardware push < ./hardware-data.json
> 2020/06/17 14:12:45 Hardware data pushed successfully
```

## Possible Solution

I don't know.

## Steps to Reproduce (for bugs)

See above.

## Context

The extra lines get dumped into the terminal when pasting, which is inconvenient and confusing.

## Your Environment

n/a

**Comment by DailyAlice** [comment]
hmmmm...sure. I can play around a bit with some styling, or just separate the command from its response.

**Comment by DailyAlice** [comment]
working on this on a branch - have done a first pass at the ones I found in the _Setups_ section.

https://github.com/DailyAlice/tinkerbell-docs/commit/18288630a6403fbcd78d1b10959251cf9dbeae0e

Wondering if I should also take a look at the _CLI Reference_ section with the same considerations.

**Comment by DailyAlice** [comment]
I think the context of the example commands and responses for the cli docs makes it not quite as annoying. Gonna go ahead without changing those.

**Comment by DailyAlice** [comment]
update is live. Closing! 🎉
