### ISSUE TITLE
Need content at https://docs.tinkerbell.org/services/

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell-docs#36]
Hi @thomcrowe 

@jacobsmith928 suggested, instead of 404 (or redirect to first child) for https://docs.tinkerbell.org/services/ , can we put up content?

LMK what you think. If putting up content agreed, I'll create issues for other similiar case:
https://docs.tinkerbell.org/setup/
https://docs.tinkerbell.org/examples/
https://docs.tinkerbell.org/cli-reference/

Thanks.

**Comment by ronggur** [comment]
Parent page with content is possible in MKDOCS

**Comment by DailyAlice** [comment]
it is, but we currently don't have much need content-wise for it. Is there something specific you are worried about?

**Comment by felixwidjaja** [comment]
Hi @DailyAlice the concern is these 4 links are 404. And its' hurting SEO.
```
https://docs.tinkerbell.org/services/
https://docs.tinkerbell.org/setup/
https://docs.tinkerbell.org/examples/
https://docs.tinkerbell.org/cli-reference/
```
Browsing those landing pages in https://docs.tinkerbell.org/ is not "clickable". So, I would suggest just have simple intro <p> content and summarize the sub pages & links there? 

I'm open to better ideas.

Thanks.

**Comment by DailyAlice** [comment]
where are people getting the 404s from? nothing links to those pages and they are only accessible if you modify the URL in the browser itself. Unless we're linking them somewhere that I'm not aware of?

**Comment by felixwidjaja** [comment]
Unfortunately not people. It's Google Search Console.

**Comment by DailyAlice** [comment]
is it in the sitemap? I'm just struggling to understand where it's picking it up from. I'm against adding pages that just have filler/summary content that isn't very informational or is too short.

**Comment by jacobsmith928** [comment]
@DailyAlice happy to review this with you live as needed.
