### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by ronggur** [tinkerbell/tinkerbell-docs#4]
@Geri docs.tinkerbell please use this font

@import url(“//cloud.typography.com/6193438/7900212/css/fonts.css”);

then use it for text, heading, label, etc except for code format

$font-family:“Gotham A”, “Gotham B”, Helvetica, Roboto, Arial, sans-serif;

**Comment by geriadam** [comment]
![image](https://user-images.githubusercontent.com/29569530/93791583-a266e880-fc5e-11ea-9ce5-07a24e2c12d4.png)
have an issue

**Comment by thomcrowe** [comment]
![image](https://user-images.githubusercontent.com/7960458/93813644-0c5c9f00-fc19-11ea-8d47-5b7ba75ec553.png)

Changing the fonts go under theme, add a line for font, indent the next with "text: font name" to update the fonts.
