### ISSUE TITLE
Replace Packet portions of Setup with Terraform with Equinix Metal

### ISSUE THREAD

**Issue by jeremytanner** [tinkerbell/tinkerbell-docs#47]
Replace Packet API / CLI / Terraform Provider with Equinix Metal when ready

[Equinix Metal Setup with Terraform](https://docs.tinkerbell.org/setup/packet-terraform/) Page

**Comment by DailyAlice** [comment]
To elaborate - the Packet terraform provider is being reborn as the Equinix Metal terraform provider - https://registry.terraform.io/providers/equinix/metal/latest
and 
https://github.com/equinix/terraform-provider-metal

Will need to update the doc as the new provider gains momentum.

**Comment by DailyAlice** [comment]
I'm pretty sure this was taken care of with PR https://github.com/tinkerbell/tinkerbell-docs/pull/73.

Closing! 🎉
