### ISSUE TITLE
Create robots.txt (for docs.)

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell-docs#48]
Geri,

Please create [robots.txt](https://github.com/tinkerbell/tinkerbell-docs/files/5686584/robots.txt) in https://docs.tinkerbell.org/robots.txt

**Comment by felixwidjaja** [comment]
Unfortunately, it's not working yet. https://docs.tinkerbell.org/robots.txt
@ronggur do you know how to put robots.txt in the root of MKDOCS?

**Comment by ronggur** [comment]
@felixwidjaja I can see it

![image](https://user-images.githubusercontent.com/780024/102173139-f59eaf00-3ecc-11eb-8457-0f7926286567.png)

**Comment by felixwidjaja** [comment]
Thank you. Sorry it was cache 👍
