### ISSUE TITLE
Missing "vagrant-setup-vbox-worker.png"

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell-docs#49]
## Expected Behaviour
Image showing

## Current Behaviour
Image missing
![image](https://user-images.githubusercontent.com/4198376/102046720-734fb580-3e0e-11eb-82d6-fa97747daefb.png)

## Possible Solution
URL changed?
or, just reupload?

## Steps to Reproduce (for bugs)

1. Visit https://docs.tinkerbell.org/services/osie/

**Comment by DailyAlice** [comment]
Thanks @felixwidjaja!
