### ISSUE TITLE
Document deployment via docker-compose / installation script

### ISSUE THREAD

**Issue by nicklasfrahm** [tinkerbell/tinkerbell-docs#60]
Currently, the documentation only provides information about how to set up Tinkerbell in a virtualized environment or on Equinix Metal. It might be nice to add some documentation for how to set it up with `docker-compose` on a host that already exists inside the network.

When adding this to the docs, I am wondering if there is a smart way of embedding the content of the [docker-compose.yml] from the sandbox repository to the documentation, such that it updates automatically and does not get out of date. Maybe we could avoid this altogether add an installation script, that users could download and execute?

Maybe users could create a `.env` file that would be sourced by the installation script, such that the `docker-compose.yml` file can be supplied with all necessary variables.

I'd be happy to implement this if you can give me some input on how you imagine this.

**Comment by tstromberg** [comment]
I think this sounds like a great idea, personally -- but am admittedly ignorant about `docker compose`. Any thoughts, @thebsdbox ?

**Comment by jacobweinstock** [comment]
This PR https://github.com/tinkerbell/sandbox/pull/90 should help with this. There is a quickstart for just docker-compose [here](https://github.com/jacobweinstock/sandbox/blob/one-touch-sandbox/docs/quickstarts/COMPOSE.md) and there there's some documentation on what's going on under the hood in docker-compose [here](https://github.com/jacobweinstock/sandbox/blob/one-touch-sandbox/docs/CONTRIBUTING.md)
