### ISSUE TITLE
Remove cli generated reference

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tinkerbell-docs#70]
We are deeply re-shaping the CLI right now

https://github.com/tinkerbell/tink/issues/405
https://github.com/tinkerbell/tink/issues/425
https://github.com/tinkerbell/tink/issues/426

And the fact that we do not have a good way to automatically keep this section
up to date with a particular version of tinkebell/tink makes the maintenance not
that fun

**Comment by gianarb** [comment]
any thought about it @DailyAlice ? Should we remove it or not? Or can we figure out how to automate that part somehow?

**Comment by thebsdbox** [comment]
You mean remove things like [https://docs.tinkerbell.org/cli-reference/hardware/](https://docs.tinkerbell.org/cli-reference/hardware/) ? 

I agree that it is going to be hard as documentation to maintain... and I don't know what we can do to make that easier. It seems like good documentation that it would be a shame to lose though :-(

**Comment by gianarb** [comment]
Well, you don't use it, you have the same, but up to date via `tink --help` :) we can mention it in the `tink-cli` document

**Comment by mmlb** [comment]
:+1: to have equivalent or better docs in tink --help (I'd love a man page)

**Comment by gianarb** [comment]
I will open a PR to remove those files.
About man cobra can generate it and o think we exposed that capability
already.

**Comment by DailyAlice** [comment]
I'm good with having better `tink --help` in favor of a CLI Reference in docs. And, if after the changes, we see a need for something closer to these docs, we can always make new ones.

**Comment by DailyAlice** [comment]
I started to work on removal on a branch - https://github.com/DailyAlice/tinkerbell-docs/tree/cli-ref-removal

Think I might just add a line about using `tink --help` in the Tink CLI doc, and maybe also expand on getting the Tink CLI up and running with tink-server.
