### ISSUE TITLE
Operating System section -> Create raw image with Packer

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tinkerbell-docs#92]
In the `Deploying Operating Systems` section of the docs, add in a document that details the basic usage of Packer to create a raw image (can be compressed with gz afterwards). Followed by the basic workflow required to deploy this image to a target machine.

**Comment by DailyAlice** [comment]
Just a note - I went ahead and merged the PR that contained the bulk of the content https://github.com/tinkerbell/tinkerbell-docs/pull/100.

I was going to put out a PR to add it to mkdocs.yml but got kinda involved in editing it, so didn't get it done. I do have a branch going though, and I should be able to get it done tomorrow. (Sorry!)

**Comment by Cbkhare** [comment]
https://github.com/tinkerbell/tinkerbell-docs/pull/100 is merged
